%%{init: {'flowchart': {'htmlLabels': false}} }%%
graph TD
  classDef product fill:#e8f5e9,stroke:#2e7d32,color:#1b5e20,stroke-width:1px;
  classDef process fill:#e3f2fd,stroke:#1565c0,color:#0d47a1,stroke-width:1px;
  classDef unknown fill:#fff3e0,stroke:#ef6c00,color:#e65100,stroke-width:1px;
  classDef multi_producer_product fill:#ffebee,stroke:#c62828,color:#b71c1c,stroke-width:2px;
  ps_test_process["ps_test_process
(process)"]
  class ps_test_process process;